title: VeloMart
description: "Your One-Stop Shop for Home & Lifestyle Essentials"
theme: minima  # Or another Jekyll theme
baseurl: ""  # Change this if using a subdirectory
url: "https://invirenz.github.io/VeloMart/"  # Update with your actual GitHub Pages URL

# Author & Socials (Optional)
author: "Michael Joshua Kinsey"
github_username: "invirenz"

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
